services:
  mockaws:
    build: https://github.com/namse/mockaws.git
    container_name: mockaws
    ports:
      - "4566:4566"
    environment:
      - PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
