services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-local
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSIST=0
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
      - ./binary:/binary:ro  # ImageMagick 바이너리 디렉토리 마운트
