/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAgreementRouteImport } from './routes/terms-agreement'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'

const TermsAgreementRoute = TermsAgreementRouteImport.update({
  id: '/terms-agreement',
  path: '/terms-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/terms-agreement': typeof TermsAgreementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/terms-agreement': typeof TermsAgreementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/terms-agreement': typeof TermsAgreementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/terms-agreement'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/terms-agreement'
  id: '__root__' | '/' | '/studio' | '/terms-agreement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  TermsAgreementRoute: typeof TermsAgreementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-agreement': {
      id: '/terms-agreement'
      path: '/terms-agreement'
      fullPath: '/terms-agreement'
      preLoaderRoute: typeof TermsAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  TermsAgreementRoute: TermsAgreementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
