import { parseTypeScriptSchema } from "./schema-gen/typescript-type-parser";
import { generateSchemaCRUD } from "./schema-gen/schema-crud-generator";
import { writeFileSync } from "fs";

export function generateSchema(inputPath: string, outputPath: string): void {
  const schema = parseTypeScriptSchema(inputPath);

  if (schema.documents.size === 0) {
    throw new Error("No documents found in the schema file");
  }

  // Generate CRUD functions
  const crudCode = generateSchemaCRUD(schema);

  // Combine everything
  const fullOutput = `// Auto-generated database functions
// Generated from: ${inputPath}
// Do not edit this file directly
// Generated at: ${new Date().toISOString()}

${crudCode}
`;

  writeFileSync(outputPath, fullOutput);
}
