// Auto-generated CRUD functions
// Generated from: ../db/src/schema.ts
// Do not edit this file directly

export type Docs = {
    session: {
        // pk
        id: string;
        
        userId: string;
    }
}

import { dbClient } from './index.js';
import { GetCommand, PutCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';

export async function getSession({id}: {id: string}) {
    const result = await dbClient.get({
        TableName: 'main',
        Key: {
            $p: `session/id=${id}`,
            $s: '_'
        }
    });
    
    return result.Item;
}

export async function putSession(session: Docs['session']) {
    await dbClient.put({
        TableName: 'main',
        Item: {
            $p: `session/id=${session.id}`,
            $s: '_',
            ...session
        }
    });
}

export async function deleteSession({id}: {id: string}) {
    // TODO: Implement deleteSession
    // Delete session from database where id = id
    throw new Error('Not implemented');
}

export async function listSessions(options?: {limit?: number; offset?: number}) {
    // TODO: Implement listSessions
    // Query database for all session records with pagination
    throw new Error('Not implemented');
}

