name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PULUMI_BACKEND_URL: s3://pulumi-state-bucket-namvas
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          fe/package-lock.json
          shared/package-lock.json
    
    # Install dependencies
    - name: Install backend dependencies
      run: |
        cd be
        bun install
    
    - name: Install frontend dependencies
      run: |
        cd fe
        npm ci
    
    - name: Install shared dependencies
      run: |
        cd shared
        npm ci
    
    - name: Install db dependencies
      run: |
        cd db
        npm ci
    
    # Run tests
    - name: Run backend linting (LLRT compatibility check)
      run: |
        cd be
        bun run lint
    
    - name: Run backend tests
      run: |
        cd be
        bun test
    
    - name: Run frontend tests
      run: |
        cd fe
        npm test
    
    - name: Run db tests
      run: |
        cd db
        npm test
    
    # Build
    - name: Build backend for LLRT
      run: |
        cd be
        bun run build:llrt
    
    - name: Build frontend
      run: |
        cd fe
        npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          fe/package-lock.json
          infrastructure/package-lock.json
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Install Pulumi CLI
      uses: pulumi/actions@v5
    
    # Install dependencies
    - name: Install backend dependencies
      run: |
        cd be
        bun install
    
    - name: Install frontend dependencies
      run: |
        cd fe
        npm ci
    
    - name: Install infrastructure dependencies
      run: |
        cd infrastructure
        npm ci
    
    # Build
    - name: Build backend for LLRT
      run: |
        cd be
        bun run build:llrt
    
    - name: Build frontend
      run: |
        cd fe
        npm run build
    
    # Deploy infrastructure
    - name: Deploy with Pulumi
      run: |
        cd infrastructure
        pulumi stack select dev --create
        pulumi up --yes
    
    # Upload frontend to S3
    - name: Upload frontend to S3
      run: |
        cd infrastructure
        BUCKET_NAME=$(pulumi stack output frontendBucketName)
        aws s3 sync ../fe/dist/ s3://$BUCKET_NAME --delete
    
    # Invalidate CloudFront cache
    - name: Invalidate CloudFront cache
      run: |
        cd infrastructure
        DISTRIBUTION_ID=$(pulumi stack output cloudFrontDistributionId)
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"